/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *nom_produit;
  GtkWidget *lieu;
  GtkWidget *fournisseur;
  GtkObject *quantite_adj;
  GtkWidget *quantite;
  GtkObject *jrf_adj;
  GtkWidget *jrf;
  GtkObject *msf_adj;
  GtkWidget *msf;
  GtkObject *anf_adj;
  GtkWidget *anf;
  GtkObject *jre_adj;
  GtkWidget *jre;
  GtkObject *mse_adj;
  GtkWidget *mse;
  GtkObject *ane_adj;
  GtkWidget *ane;
  GtkWidget *reference;
  GtkWidget *label2;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label4;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton9;
  GtkWidget *label10;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *button3afficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label13;
  GtkWidget *button2quitter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *button1modif;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label26;
  GtkWidget *button1ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 700, 700);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);
  gtk_widget_set_size_request (fixed1, 700, 800);

  nom_produit = gtk_entry_new ();
  gtk_widget_show (nom_produit);
  gtk_fixed_put (GTK_FIXED (fixed1), nom_produit, 176, 136);
  gtk_widget_set_size_request (nom_produit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_produit), 8226);

  lieu = gtk_entry_new ();
  gtk_widget_show (lieu);
  gtk_fixed_put (GTK_FIXED (fixed1), lieu, 176, 200);
  gtk_widget_set_size_request (lieu, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (lieu), 8226);

  fournisseur = gtk_entry_new ();
  gtk_widget_show (fournisseur);
  gtk_fixed_put (GTK_FIXED (fixed1), fournisseur, 176, 256);
  gtk_widget_set_size_request (fournisseur, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (fournisseur), 8226);

  quantite_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  quantite = gtk_spin_button_new (GTK_ADJUSTMENT (quantite_adj), 1, 0);
  gtk_widget_show (quantite);
  gtk_fixed_put (GTK_FIXED (fixed1), quantite, 200, 304);
  gtk_widget_set_size_request (quantite, 60, 27);

  jrf_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jrf = gtk_spin_button_new (GTK_ADJUSTMENT (jrf_adj), 1, 0);
  gtk_widget_show (jrf);
  gtk_fixed_put (GTK_FIXED (fixed1), jrf, 176, 432);
  gtk_widget_set_size_request (jrf, 60, 27);

  msf_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  msf = gtk_spin_button_new (GTK_ADJUSTMENT (msf_adj), 1, 0);
  gtk_widget_show (msf);
  gtk_fixed_put (GTK_FIXED (fixed1), msf, 280, 432);
  gtk_widget_set_size_request (msf, 60, 27);

  anf_adj = gtk_adjustment_new (1, 1970, 2100, 1, 10, 10);
  anf = gtk_spin_button_new (GTK_ADJUSTMENT (anf_adj), 1, 0);
  gtk_widget_show (anf);
  gtk_fixed_put (GTK_FIXED (fixed1), anf, 368, 432);
  gtk_widget_set_size_request (anf, 60, 27);

  jre_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jre = gtk_spin_button_new (GTK_ADJUSTMENT (jre_adj), 1, 0);
  gtk_widget_show (jre);
  gtk_fixed_put (GTK_FIXED (fixed1), jre, 176, 496);
  gtk_widget_set_size_request (jre, 60, 27);

  mse_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mse = gtk_spin_button_new (GTK_ADJUSTMENT (mse_adj), 1, 0);
  gtk_widget_show (mse);
  gtk_fixed_put (GTK_FIXED (fixed1), mse, 272, 496);
  gtk_widget_set_size_request (mse, 60, 27);

  ane_adj = gtk_adjustment_new (1, 1970, 2100, 1, 10, 10);
  ane = gtk_spin_button_new (GTK_ADJUSTMENT (ane_adj), 1, 0);
  gtk_widget_show (ane);
  gtk_fixed_put (GTK_FIXED (fixed1), ane, 360, 496);
  gtk_widget_set_size_request (ane, 60, 27);

  reference = gtk_entry_new ();
  gtk_widget_show (reference);
  gtk_fixed_put (GTK_FIXED (fixed1), reference, 168, 544);
  gtk_widget_set_size_request (reference, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (reference), 8226);

  label2 = gtk_label_new (_("Nom produit"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 128);
  gtk_widget_set_size_request (label2, 104, 33);

  label5 = gtk_label_new (_("Quantit\303\251"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 24, 296);
  gtk_widget_set_size_request (label5, 104, 32);

  label6 = gtk_label_new (_("Unit\303\251"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 32, 360);
  gtk_widget_set_size_request (label6, 72, 32);

  label7 = gtk_label_new (_("Date de \nFabrication"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 24, 416);
  gtk_widget_set_size_request (label7, 104, 47);

  label8 = gtk_label_new (_("Date d'\nexpiration"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 8, 480);
  gtk_widget_set_size_request (label8, 120, 56);

  label9 = gtk_label_new (_("Reference"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 8, 544);
  gtk_widget_set_size_request (label9, 120, 24);

  label4 = gtk_label_new (_("Fournisseur"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 32, 256);
  gtk_widget_set_size_request (label4, 120, 24);

  label3 = gtk_label_new (_("Lieu de fabrication"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 16, 200);
  gtk_widget_set_size_request (label3, 144, 32);

  label1 = gtk_label_new (_("Type"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 72);
  gtk_widget_set_size_request (label1, 41, 17);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Produit laitien"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 120, 48);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Cereal"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 240, 48);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Produit sucr\303\251s"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton3, 360, 48);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Boissons"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton4, 120, 72);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("L\303\251gumes"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton5, 240, 72);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Fruits"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton6, 360, 72);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Matiere grasse"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton7, 120, 96);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Viandes"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton8, 240, 96);
  gtk_widget_set_size_request (radiobutton8, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("Poissons"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton9, 360, 96);
  gtk_widget_set_size_request (radiobutton9, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  label10 = gtk_label_new (_("Ajout Stock"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 192, 8);
  gtk_widget_set_size_request (label10, 144, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Kg"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 184, 368);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Piece"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton2, 344, 368);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  button3afficher = gtk_button_new ();
  gtk_widget_show (button3afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), button3afficher, 480, 608);
  gtk_widget_set_size_request (button3afficher, 176, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3afficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-paste", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);

  button2quitter = gtk_button_new ();
  gtk_widget_show (button2quitter);
  gtk_fixed_put (GTK_FIXED (fixed1), button2quitter, 560, 8);
  gtk_widget_set_size_request (button2quitter, 104, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2quitter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  button1modif = gtk_button_new ();
  gtk_widget_show (button1modif);
  gtk_fixed_put (GTK_FIXED (fixed1), button1modif, 248, 680);
  gtk_widget_set_size_request (button1modif, 168, 56);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button1modif), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);

  button1ajouter = gtk_button_new ();
  gtk_widget_show (button1ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button1ajouter, 32, 608);
  gtk_widget_set_size_request (button1ajouter, 168, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (on_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton9, "toggled",
                    G_CALLBACK (on_radiobutton9_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button3afficher, "clicked",
                    G_CALLBACK (on_button3afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2quitter, "clicked",
                    G_CALLBACK (on_button2quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1modif, "clicked",
                    G_CALLBACK (on_button1modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1ajouter, "clicked",
                    G_CALLBACK (on_button1ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, nom_produit, "nom_produit");
  GLADE_HOOKUP_OBJECT (window1, lieu, "lieu");
  GLADE_HOOKUP_OBJECT (window1, fournisseur, "fournisseur");
  GLADE_HOOKUP_OBJECT (window1, quantite, "quantite");
  GLADE_HOOKUP_OBJECT (window1, jrf, "jrf");
  GLADE_HOOKUP_OBJECT (window1, msf, "msf");
  GLADE_HOOKUP_OBJECT (window1, anf, "anf");
  GLADE_HOOKUP_OBJECT (window1, jre, "jre");
  GLADE_HOOKUP_OBJECT (window1, mse, "mse");
  GLADE_HOOKUP_OBJECT (window1, ane, "ane");
  GLADE_HOOKUP_OBJECT (window1, reference, "reference");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window1, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window1, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window1, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window1, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window1, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window1, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (window1, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (window1, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window1, button3afficher, "button3afficher");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, button2quitter, "button2quitter");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, button1modif, "button1modif");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image10, "image10");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, button1ajouter, "button1ajouter");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");

  return window1;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed2;
  GtkWidget *label14;
  GtkWidget *dialog_action_area1;
  GtkWidget *closebutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog1), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed2, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("Stock ajouter avec success"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 40, 64);
  gtk_widget_set_size_request (label14, 224, 40);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (on_closebutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (dialog1, label14, "label14");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, closebutton1, "closebutton1");

  return dialog1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed3;
  GtkWidget *label15;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton2;

  dialog2 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed3, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("Vous devez remplire tous les champs"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 8, 96);
  gtk_widget_set_size_request (label15, 272, 48);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton2, "clicked",
                    G_CALLBACK (on_closebutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (dialog2, label15, "label15");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, closebutton2, "closebutton2");

  return dialog2;
}

GtkWidget*
create_afficher_stock (void)
{
  GtkWidget *afficher_stock;
  GtkWidget *fixed4;
  GtkWidget *treeviewgestionstock;
  GtkWidget *button1modifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label21;
  GtkWidget *button2supprimer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label22;
  GtkWidget *button3repture;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label23;
  GtkWidget *button3retour;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label24;
  GtkWidget *entry1recherche;
  GtkWidget *button1recherche;
  GtkWidget *image9;

  afficher_stock = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher_stock), _("Afficher Stock"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (afficher_stock), fixed4);

  treeviewgestionstock = gtk_tree_view_new ();
  gtk_widget_show (treeviewgestionstock);
  gtk_fixed_put (GTK_FIXED (fixed4), treeviewgestionstock, 8, 80);
  gtk_widget_set_size_request (treeviewgestionstock, 784, 320);

  button1modifier = gtk_button_new ();
  gtk_widget_show (button1modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), button1modifier, 136, 400);
  gtk_widget_set_size_request (button1modifier, 88, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button1modifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  button2supprimer = gtk_button_new ();
  gtk_widget_show (button2supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), button2supprimer, 224, 400);
  gtk_widget_set_size_request (button2supprimer, 98, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button2supprimer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox5), label22, FALSE, FALSE, 0);

  button3repture = gtk_button_new ();
  gtk_widget_show (button3repture);
  gtk_fixed_put (GTK_FIXED (fixed4), button3repture, 328, 400);
  gtk_widget_set_size_request (button3repture, 216, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button3repture), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Afficher repture de stock"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox6), label23, FALSE, FALSE, 0);

  button3retour = gtk_button_new ();
  gtk_widget_show (button3retour);
  gtk_fixed_put (GTK_FIXED (fixed4), button3retour, 552, 400);
  gtk_widget_set_size_request (button3retour, 98, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button3retour), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox7), label24, FALSE, FALSE, 0);

  entry1recherche = gtk_entry_new ();
  gtk_widget_show (entry1recherche);
  gtk_fixed_put (GTK_FIXED (fixed4), entry1recherche, 272, 32);
  gtk_widget_set_size_request (entry1recherche, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1recherche), 8226);

  button1recherche = gtk_button_new ();
  gtk_widget_show (button1recherche);
  gtk_fixed_put (GTK_FIXED (fixed4), button1recherche, 432, 32);
  gtk_widget_set_size_request (button1recherche, 40, 32);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button1recherche), image9);

  g_signal_connect ((gpointer) treeviewgestionstock, "row_activated",
                    G_CALLBACK (on_treeviewgestionstock_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1modifier, "clicked",
                    G_CALLBACK (on_button1modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2supprimer, "clicked",
                    G_CALLBACK (on_button2supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3repture, "clicked",
                    G_CALLBACK (on_button3repture_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3retour, "clicked",
                    G_CALLBACK (on_button3retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1recherche, "clicked",
                    G_CALLBACK (on_button1recherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_stock, afficher_stock, "afficher_stock");
  GLADE_HOOKUP_OBJECT (afficher_stock, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (afficher_stock, treeviewgestionstock, "treeviewgestionstock");
  GLADE_HOOKUP_OBJECT (afficher_stock, button1modifier, "button1modifier");
  GLADE_HOOKUP_OBJECT (afficher_stock, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (afficher_stock, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (afficher_stock, image4, "image4");
  GLADE_HOOKUP_OBJECT (afficher_stock, label21, "label21");
  GLADE_HOOKUP_OBJECT (afficher_stock, button2supprimer, "button2supprimer");
  GLADE_HOOKUP_OBJECT (afficher_stock, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (afficher_stock, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (afficher_stock, image5, "image5");
  GLADE_HOOKUP_OBJECT (afficher_stock, label22, "label22");
  GLADE_HOOKUP_OBJECT (afficher_stock, button3repture, "button3repture");
  GLADE_HOOKUP_OBJECT (afficher_stock, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (afficher_stock, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (afficher_stock, image6, "image6");
  GLADE_HOOKUP_OBJECT (afficher_stock, label23, "label23");
  GLADE_HOOKUP_OBJECT (afficher_stock, button3retour, "button3retour");
  GLADE_HOOKUP_OBJECT (afficher_stock, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (afficher_stock, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (afficher_stock, image7, "image7");
  GLADE_HOOKUP_OBJECT (afficher_stock, label24, "label24");
  GLADE_HOOKUP_OBJECT (afficher_stock, entry1recherche, "entry1recherche");
  GLADE_HOOKUP_OBJECT (afficher_stock, button1recherche, "button1recherche");
  GLADE_HOOKUP_OBJECT (afficher_stock, image9, "image9");

  return afficher_stock;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *button2retour2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label25;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window2), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 16, 88);
  gtk_widget_set_size_request (treeview1, 704, 256);

  button2retour2 = gtk_button_new ();
  gtk_widget_show (button2retour2);
  gtk_fixed_put (GTK_FIXED (fixed5), button2retour2, 328, 368);
  gtk_widget_set_size_request (button2retour2, 88, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button2retour2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox8), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button2retour2, "clicked",
                    G_CALLBACK (on_button2retour2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, button2retour2, "button2retour2");
  GLADE_HOOKUP_OBJECT (window2, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window2, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window2, image8, "image8");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");

  return window2;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed7;
  GtkWidget *buttongotoajouter;
  GtkWidget *buttongotomodifier;
  GtkWidget *buttongotoafficher;
  GtkWidget *buttongotosupprimer;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window4), fixed7);
  gtk_widget_set_size_request (fixed7, 360, 349);

  buttongotoajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttongotoajouter);
  gtk_fixed_put (GTK_FIXED (fixed7), buttongotoajouter, 144, 48);
  gtk_widget_set_size_request (buttongotoajouter, 96, 40);

  buttongotomodifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (buttongotomodifier);
  gtk_fixed_put (GTK_FIXED (fixed7), buttongotomodifier, 144, 112);
  gtk_widget_set_size_request (buttongotomodifier, 96, 40);

  buttongotoafficher = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (buttongotoafficher);
  gtk_fixed_put (GTK_FIXED (fixed7), buttongotoafficher, 144, 168);
  gtk_widget_set_size_request (buttongotoafficher, 96, 40);

  buttongotosupprimer = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (buttongotosupprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), buttongotosupprimer, 144, 224);
  gtk_widget_set_size_request (buttongotosupprimer, 96, 40);

  g_signal_connect ((gpointer) buttongotoajouter, "clicked",
                    G_CALLBACK (on_buttongotoajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongotomodifier, "clicked",
                    G_CALLBACK (on_buttongotomodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongotoafficher, "clicked",
                    G_CALLBACK (on_buttongotoafficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongotosupprimer, "clicked",
                    G_CALLBACK (on_buttongotosupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window4, buttongotoajouter, "buttongotoajouter");
  GLADE_HOOKUP_OBJECT (window4, buttongotomodifier, "buttongotomodifier");
  GLADE_HOOKUP_OBJECT (window4, buttongotoafficher, "buttongotoafficher");
  GLADE_HOOKUP_OBJECT (window4, buttongotosupprimer, "buttongotosupprimer");

  return window4;
}

